version: '3.8'

services:
  mqtt:
    image: eclipse-mosquitto:latest
    ports:
      - "${MQTT_PORT}:1883"      # 1883:1883 from .env MQTT_PORT=1883
      - "${MQTT_WS_PORT}:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config

  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT}:5000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - MQTT_BROKER=${MQTT_BROKER}
    depends_on:
      - db
      - mqtt

  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT}:3000"
    environment:
      - API_URL=${API_URL}
    depends_on:
      - backend

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
