# .github/workflows/docker-build.yml
name: Build Docker Images

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # or whatever version you use

      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      - name: Run backend tests
        run: |
          cd backend
          npm test # or: npx jest / npx mocha etc.

      - name: Build backend Docker image
        run: docker build -t my-backend ./backend

      - name: Build frontend Docker image
        run: docker build -t my-frontend ./frontend
